# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Compute the inverse of a matrix
#'
#'@param A a matrix
#'
#'@export
invC <- function(A) {
    .Call(`_mypkgr_invC`, A)
}

#'@rdname mvnpdf
#'@order 7
#'@export
mvnpdfC_LeChat <- function(x, mean, varcovM, Log = TRUE) {
    .Call(`_mypkgr_mvnpdfC_LeChat`, x, mean, varcovM, Log)
}

#'@details the implementation of mvnpdfoptimC based on the implementation
#'from Nino Hardt and Dicko Ahmadou
#'http://gallery.rcpp.org/articles/dmvnorm_arma/ (accessed in August 2014)
#'
#'@rdname mvnpdf
#'@order 6
#'@export
#'
mvnpdfoptimC <- function(x, mean, varcovM, Log = TRUE) {
    .Call(`_mypkgr_mvnpdfoptimC`, x, mean, varcovM, Log)
}

#'@rdname mvnpdf
#'@order 5
#'@export
mvnpdfsmartC <- function(x, mean, varcovM, Log = TRUE) {
    .Call(`_mypkgr_mvnpdfsmartC`, x, mean, varcovM, Log)
}

#' Multiplies vector by 2
#'
#' Example Rcpp function that multiplies its vector input by 2.
#'
#'@param x a numeric vector
#'
#'@export
timesTwo <- function(x) {
    .Call(`_mypkgr_timesTwo`, x)
}

